- name: Disables password authentication for SSH
  hosts: "*"

  tasks:
    - name: SSH Password Authentication
      shell: |
        cd /etc/ssh
        sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/g' /etc/ssh/sshd_config
        systemctl restart ssh
